import { PresetArchitecture, CryptoNodeData, CryptoEdgeData } from '../src/types/cryptoGraph.js';
import { calculateNodeRisk } from './riskModel.js';

function buildNode(data: Omit<CryptoNodeData, 'risk_score' | 'hndl_score' | 'hndl_exposure_horizon'>): CryptoNodeData {
  const riskInfo = calculateNodeRisk(data);
  return {
    ...data,
    ...riskInfo,
  } as CryptoNodeData;
}

export const PRESET_FINTECH_PAYMENT: PresetArchitecture = {
  id: 'fintech-payment-core',
  name: 'Tier-1 Banking & Payment Processing Core',
  industry: 'Fintech & Payment Services',
  description: 'Enterprise PCI-DSS microservices processing credit card authorizations, tokenization, settlement, and legacy bank partner integrations.',
  graph: {
    nodes: [
      buildNode({
        id: 'node-edge-ingress',
        label: 'Edge API Gateway',
        type: 'System',
        crypto_primitive: 'TLS_ECDHE_RSA_WITH_AES_256_GCM',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 7,
        recommended_pqc: 'X25519 + ML-KEM-768 Hybrid Key Exchange',
        nist_standard: 'NIST FIPS 203',
        migration_phase: 1,
        owner: 'SecOps & Edge Infrastructure',
        location: 'AWS us-east-1 (CloudFront / ALB)',
        compliance_tags: ['PCI-DSS v4.0', 'NIST SP 800-52r2'],
        notes: 'Terminates public client traffic. Prime target for Harvest-Now-Decrypt-Later eavesdropping.',
      }),
      buildNode({
        id: 'node-auth-service',
        label: 'Auth-Service (OIDC/JWT)',
        type: 'Service',
        crypto_primitive: 'JWT with ECDSA (secp256r1)',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 10,
        recommended_pqc: 'ML-DSA-65 (FIPS 204) Dual Signed Tokens',
        nist_standard: 'NIST FIPS 204',
        migration_phase: 1,
        owner: 'Identity & Access Management',
        location: 'EKS Cluster / IAM Pods',
        compliance_tags: ['NIST SP 800-63B', 'ISO 27001'],
        notes: 'Issues bearer tokens. Vulnerable to Shor algorithm forging quantum private key signatures.',
      }),
      buildNode({
        id: 'node-payment-gw',
        label: 'Payment-Gateway Service',
        type: 'Service',
        crypto_primitive: 'RSA-2048 / PKCS#1 v1.5',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 15,
        recommended_pqc: 'ML-KEM-768 & ML-DSA-65',
        nist_standard: 'NIST FIPS 203 / 204',
        migration_phase: 2,
        owner: 'Payments Engineering',
        location: 'PCI-Enclave Kubernetes',
        compliance_tags: ['PCI-DSS v4.0 Req 3.5', 'EMVCo'],
        notes: 'Cardholder transaction routing. 15-year audit trail makes HNDL risk catastrophic.',
      }),
      buildNode({
        id: 'node-legacy-partner',
        label: 'Legacy-Partner-API (SWIFT/CoreBank)',
        type: 'Service',
        crypto_primitive: 'TLS 1.1 / Fixed RSA-1024 Handshake',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 20,
        is_blocker: true,
        blocker_reason: 'Legacy upstream correspondent banking partner strictly hardcodes TLS 1.1 with RSA-1024. Rejects PQC/TLS 1.3 handshakes.',
        recommended_pqc: 'Deploy PQC Decoupling Transcoding Proxy / Shim Gateway',
        nist_standard: 'NIST IR 8547 / RFC 9180',
        migration_phase: 2,
        owner: 'External Interbank Partner (Consortium)',
        location: 'Dedicated Cross-Connect Leased Line',
        compliance_tags: ['SWIFT CSP', 'Legacy BACS'],
        resolution_strategy: 'Deploy PQC-aware Termination Proxy that translates internal ML-KEM/ML-DSA traffic into isolated legacy sandbox protocol.',
        notes: 'HARD BLOCKER: Cannot directly upgrade partner client. Requires shim proxy pattern.',
      }),
      buildNode({
        id: 'node-token-vault',
        label: 'Card Token Vault',
        type: 'Service',
        crypto_primitive: 'AES-128-CBC with RSA-2048 KEK',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 25,
        recommended_pqc: 'AES-256-GCM with ML-KEM-1024 Envelope Encryption',
        nist_standard: 'NIST FIPS 203 / SP 800-38D',
        migration_phase: 2,
        owner: 'Core Tokenization Team',
        location: 'FIPS 140-3 HSM Dedicated VPC',
        compliance_tags: ['PCI-DSS v4.0 Tokenization Spec'],
        notes: 'Stores primary account numbers (PAN). Grover algorithm cuts AES-128 to 64-bit effective security. 25-year retention is extreme HNDL vulnerability.',
      }),
      buildNode({
        id: 'node-db-cluster',
        label: 'DB-Cluster (Aurora PostgreSQL)',
        type: 'System',
        crypto_primitive: 'AES-128 TDE / TLS 1.2 ECDHE',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 15,
        recommended_pqc: 'AES-256-XTS TDE + Post-Quantum mTLS (ML-KEM)',
        nist_standard: 'NIST FIPS 203 / CNSA 2.0',
        migration_phase: 2,
        owner: 'Database Reliability Engineering',
        location: 'Multi-AZ Encrypted Storage',
        compliance_tags: ['SOC 2 Type II', 'PCI-DSS'],
        notes: 'Core financial transactions database. Needs transparent data re-encryption to AES-256.',
      }),
      buildNode({
        id: 'node-hsm-root',
        label: 'Hardware Security Module (HSM Cluster)',
        type: 'Key',
        crypto_primitive: 'RSA-4096 Root CA & KEK',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 25,
        recommended_pqc: 'SLH-DSA-256s (FIPS 205) / ML-DSA-87 (FIPS 204)',
        nist_standard: 'NIST FIPS 205',
        migration_phase: 3,
        owner: 'Enterprise Security Architecture',
        location: 'Equinix On-Prem Hardware HSMs',
        compliance_tags: ['FIPS 140-2 Level 3', 'WebTrust CA'],
        notes: 'Root of Trust for the entire organization. Firmware upgrade needed for stateless hash-based signatures.',
      }),
      buildNode({
        id: 'node-crypto-lib',
        label: 'libcrypto-standard v1.1.1',
        type: 'Library',
        crypto_primitive: 'OpenSSL 1.1.1 (Classical)',
        quantum_status: 'VULNERABLE',
        criticality: 'MEDIUM',
        data_retention_years: 5,
        is_blocker: true,
        blocker_reason: 'Deprecated OpenSSL 1.1.1 lacks PQC provider APIs and NIST FIPS 203/204/205 algorithmic implementations.',
        recommended_pqc: 'Upgrade to OpenSSL 3.4+ with liboqs-provider or BWS-CryptoAgile',
        nist_standard: 'NIST IR 8547',
        migration_phase: 1,
        owner: 'Core Platform Engineering',
        location: 'Base Docker Golden Images',
        compliance_tags: ['CVE-2023-0286', 'SBOM Compliance'],
        resolution_strategy: 'Migrate base container images to OpenSSL 3.4 with OQS (Open Quantum Safe) Provider.',
        notes: 'LIBRARY BLOCKER: Subordinate services fail PQC compilation until libcrypto is bumped.',
      }),
      buildNode({
        id: 'node-kafka-bus',
        label: 'Kafka Event Broker',
        type: 'Service',
        crypto_primitive: 'mTLS ECDSA P-256 / AES-128',
        quantum_status: 'VULNERABLE',
        criticality: 'MEDIUM',
        data_retention_years: 3,
        recommended_pqc: 'mTLS ML-KEM-768 with ML-DSA-65 Client Certs',
        nist_standard: 'NIST FIPS 203 / 204',
        migration_phase: 2,
        owner: 'Event Stream Platform Team',
        location: 'Confluent Cloud / VPC Peering',
        compliance_tags: ['Internal Security Baseline'],
        notes: 'High-throughput payment event streaming. Low retention but critical path.',
      }),
      buildNode({
        id: 'node-audit-s3',
        label: 'S3 Regulatory Archival Vault',
        type: 'System',
        crypto_primitive: 'SSE-KMS RSA-2048 Wrapper',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 30,
        recommended_pqc: 'AWS KMS Post-Quantum ML-KEM-768 Encrypted Envelopes',
        nist_standard: 'NIST FIPS 203 / CNSA 2.0',
        migration_phase: 3,
        owner: 'Compliance & Legal Archive',
        location: 'AWS S3 Glacier Vault Lock',
        compliance_tags: ['SEC Rule 17a-4', 'FINRA 4511'],
        notes: '30-year statutory data retention. Under HNDL, adversaries storing this bucket traffic will decrypt complete customer financial histories in 2030.',
      }),
    ],
    edges: [
      { id: 'e1', source: 'node-edge-ingress', target: 'node-auth-service', relationship: 'COMMUNICATES_WITH', label: 'mTLS / JWT Validation' },
      { id: 'e2', source: 'node-edge-ingress', target: 'node-payment-gw', relationship: 'COMMUNICATES_WITH', label: 'HTTP/2 REST' },
      { id: 'e3', source: 'node-payment-gw', target: 'node-token-vault', relationship: 'DEPENDS_ON', label: 'Card Tokenization RPC' },
      { id: 'e4', source: 'node-payment-gw', target: 'node-db-cluster', relationship: 'USES_ALGORITHM', label: 'Aurora SQL Connection' },
      { id: 'e5', source: 'node-payment-gw', target: 'node-legacy-partner', relationship: 'BLOCKED_BY', label: 'Blocked by TLS 1.1 Incompatibility', is_blocked: true },
      { id: 'e6', source: 'node-payment-gw', target: 'node-kafka-bus', relationship: 'COMMUNICATES_WITH', label: 'Payment Events Stream' },
      { id: 'e7', source: 'node-token-vault', target: 'node-hsm-root', relationship: 'DEPENDS_ON', label: 'Master Key Wrapping' },
      { id: 'e8', source: 'node-db-cluster', target: 'node-hsm-root', relationship: 'DEPENDS_ON', label: 'TDE Master KEK' },
      { id: 'e9', source: 'node-auth-service', target: 'node-hsm-root', relationship: 'DEPENDS_ON', label: 'JWT Signing Private Key' },
      { id: 'e10', source: 'node-auth-service', target: 'node-crypto-lib', relationship: 'BLOCKED_BY', label: 'Requires OpenSSL 3.4+ with PQC Provider', is_blocked: true },
      { id: 'e11', source: 'node-payment-gw', target: 'node-crypto-lib', relationship: 'BLOCKED_BY', label: 'Requires OpenSSL 3.4+ with PQC Provider', is_blocked: true },
      { id: 'e12', source: 'node-kafka-bus', target: 'node-audit-s3', relationship: 'COMMUNICATES_WITH', label: 'Batch Archival Sync (30yr)' },
    ],
  },
};

export const PRESET_HEALTHCARE_EHR: PresetArchitecture = {
  id: 'healthcare-ehr-cloud',
  name: 'Healthcare EHR & Medical IoT Cloud',
  industry: 'Healthcare & Life Sciences',
  description: 'HIPAA-compliant hospital electronic health records, PACS medical imaging, and telemetry gateway for connected implantable devices.',
  graph: {
    nodes: [
      buildNode({
        id: 'hc-ingress',
        label: 'Hospital Portal Ingress',
        type: 'System',
        crypto_primitive: 'TLS 1.3 ECDHE-RSA-2048',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 25,
        recommended_pqc: 'X25519 + ML-KEM-768 Hybrid',
        nist_standard: 'NIST FIPS 203',
        migration_phase: 1,
        owner: 'Digital Health Infrastructure',
        compliance_tags: ['HIPAA Omnibus', 'HITECH'],
      }),
      buildNode({
        id: 'hc-ehr-api',
        label: 'EHR Patient Record API',
        type: 'Service',
        crypto_primitive: 'SMART on FHIR / ECDSA P-384',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 50,
        recommended_pqc: 'ML-DSA-65 (FIPS 204)',
        nist_standard: 'NIST FIPS 204',
        migration_phase: 2,
        owner: 'Clinical Informatics',
        compliance_tags: ['HIPAA 50-Year Medical Retention'],
        notes: 'Life-long patient genetic and diagnostic data. 50-year retention presents extreme catastrophic HNDL risk.',
      }),
      buildNode({
        id: 'hc-pacs-store',
        label: 'PACS Imaging Store (DICOM)',
        type: 'System',
        crypto_primitive: 'AES-128-CBC Encryption at Rest',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 30,
        recommended_pqc: 'AES-256-GCM with ML-KEM-768 Wrapped DEKs',
        nist_standard: 'NIST FIPS 203',
        migration_phase: 2,
        owner: 'Radiology Engineering',
        compliance_tags: ['DICOM Part 15 / PS 3.15'],
      }),
      buildNode({
        id: 'hc-iot-gateway',
        label: 'IoT Medical Telemetry Gateway',
        type: 'Service',
        crypto_primitive: 'DTLS 1.2 ECDSA P-256',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 10,
        is_blocker: true,
        blocker_reason: 'Legacy Pacemaker & Infusion Pump firmware has hardcoded 8-bit crypto microcontrollers unable to parse 1184-byte ML-KEM ciphertexts.',
        recommended_pqc: 'Deploy Edge Micro-Proxy with Stateful PQC Compression',
        nist_standard: 'NIST IR 8547 / RFC 9180',
        migration_phase: 2,
        owner: 'Biomedical Devices Team',
        resolution_strategy: 'Install localized Hospital Edge Gateway acting as a PQC translation termination proxy for constrained embedded devices.',
        compliance_tags: ['FDA Cybersecurity Guidance for Medical Devices'],
      }),
      buildNode({
        id: 'hc-kms',
        label: 'Healthcare Enterprise KMS',
        type: 'Key',
        crypto_primitive: 'RSA-4096 Root Key',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 50,
        recommended_pqc: 'SLH-DSA-192s (FIPS 205)',
        nist_standard: 'NIST FIPS 205',
        migration_phase: 3,
        owner: 'CISO Office',
        compliance_tags: ['FIPS 140-3'],
      }),
    ],
    edges: [
      { id: 'hc-e1', source: 'hc-ingress', target: 'hc-ehr-api', relationship: 'COMMUNICATES_WITH', label: 'REST / FHIR mTLS' },
      { id: 'hc-e2', source: 'hc-ehr-api', target: 'hc-pacs-store', relationship: 'DEPENDS_ON', label: 'DICOM Object Fetch' },
      { id: 'hc-e3', source: 'hc-ehr-api', target: 'hc-iot-gateway', relationship: 'BLOCKED_BY', label: 'Blocked by Embedded Firmware Constraints', is_blocked: true },
      { id: 'hc-e4', source: 'hc-ehr-api', target: 'hc-kms', relationship: 'DEPENDS_ON', label: 'Master Key Hierarchy' },
      { id: 'hc-e5', source: 'hc-pacs-store', target: 'hc-kms', relationship: 'DEPENDS_ON', label: 'PACS Key Decryption' },
    ],
  },
};

export const PRESET_ECOMMERCE_CLOUD: PresetArchitecture = {
  id: 'ecommerce-cloud',
  name: 'Global E-Commerce & Token Vault Architecture',
  industry: 'Retail & Consumer Tech',
  description: 'High-volume microservices architecture managing storefront checkout, customer identity, payment authorization, and inventory synchronization.',
  graph: {
    nodes: [
      buildNode({
        id: 'ecom-cdn',
        label: 'Global CDN & WAF Ingress',
        type: 'System',
        crypto_primitive: 'TLS 1.3 X25519-RSA',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 3,
        recommended_pqc: 'X25519 + ML-KEM-768 Hybrid Key Exchange',
        nist_standard: 'NIST FIPS 203',
        migration_phase: 1,
      }),
      buildNode({
        id: 'ecom-checkout',
        label: 'Checkout Orchestrator',
        type: 'Service',
        crypto_primitive: 'ECDSA P-256 Signing',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 7,
        recommended_pqc: 'ML-DSA-65 (FIPS 204)',
        nist_standard: 'NIST FIPS 204',
        migration_phase: 2,
      }),
      buildNode({
        id: 'ecom-user-vault',
        label: 'Customer PII Vault',
        type: 'System',
        crypto_primitive: 'AES-128-GCM with RSA-2048 KEK',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 12,
        recommended_pqc: 'AES-256-GCM + ML-KEM-768 Envelopes',
        nist_standard: 'NIST FIPS 203',
        migration_phase: 2,
      }),
      buildNode({
        id: 'ecom-legacy-pos',
        label: 'Legacy Point-of-Sale Terminals',
        type: 'Service',
        crypto_primitive: 'DUKPT 3DES / RSA-1024',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 10,
        is_blocker: true,
        blocker_reason: 'Over 50,000 legacy hardware POS terminals lack remote firmware update capability to support post-quantum key sizes.',
        recommended_pqc: 'Deploy In-Store PQC Edge Appliance & Gateway Tokenizer',
        nist_standard: 'NIST IR 8547',
        migration_phase: 2,
      }),
      buildNode({
        id: 'ecom-kms-root',
        label: 'Cloud KMS Root Key',
        type: 'Key',
        crypto_primitive: 'RSA-4096 Asymmetric Key',
        quantum_status: 'VULNERABLE',
        criticality: 'HIGH',
        data_retention_years: 15,
        recommended_pqc: 'ML-DSA-87 / ML-KEM-1024',
        nist_standard: 'NIST FIPS 203 / 204',
        migration_phase: 3,
      }),
    ],
    edges: [
      { id: 'ec-e1', source: 'ecom-cdn', target: 'ecom-checkout', relationship: 'COMMUNICATES_WITH', label: 'gRPC mTLS' },
      { id: 'ec-e2', source: 'ecom-checkout', target: 'ecom-user-vault', relationship: 'USES_ALGORITHM', label: 'Customer Token Fetch' },
      { id: 'ec-e3', source: 'ecom-checkout', target: 'ecom-legacy-pos', relationship: 'BLOCKED_BY', label: 'Blocked by Physical POS Hardware Limitations', is_blocked: true },
      { id: 'ec-e4', source: 'ecom-user-vault', target: 'ecom-kms-root', relationship: 'DEPENDS_ON', label: 'Envelope Decryption' },
    ],
  },
};

export const ALL_PRESETS: PresetArchitecture[] = [
  PRESET_FINTECH_PAYMENT,
  PRESET_HEALTHCARE_EHR,
  PRESET_ECOMMERCE_CLOUD,
];
