import React, { useState } from 'react';
import { X, Download, Copy, Check, FileText, ShieldCheck, Award, Landmark } from 'lucide-react';
import { GraphData, RiskSummary, MigrationPlan } from '../types/cryptoGraph.js';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  graph: GraphData;
  riskSummary: RiskSummary;
  migrationPlan: MigrationPlan | null;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  graph,
  riskSummary,
  migrationPlan,
}) => {
  const [activeTab, setActiveTab] = useState<'CYCLONEDX' | 'EXECUTIVE_REPORT' | 'RAW_GRAPH' | 'FEDERAL_COMPLIANCE'>('EXECUTIVE_REPORT');
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  // Generate CycloneDX 1.6 format
  const cycloneDxOutput = JSON.stringify(
    {
      bomFormat: 'CycloneDX',
      specVersion: '1.6',
      serialNumber: `urn:uuid:${Date.now()}-camp-graph`,
      version: 1,
      metadata: {
        timestamp: new Date().toISOString(),
        tools: [
          {
            vendor: 'CAMP-Graph',
            name: 'Post-Quantum Cryptography Migration Engine',
            version: '1.0.0',
          },
        ],
        component: {
          name: 'CAMP-Graph Enterprise Asset Inventory',
          type: 'application',
        },
      },
      components: graph.nodes.map((n) => ({
        'bom-ref': n.id,
        name: n.label,
        type: n.type.toLowerCase(),
        cryptoProperties: {
          assetType: n.type === 'Library' ? 'library' : (n.type === 'Key' ? 'key' : 'algorithm'),
          algorithmProperties: {
            name: n.crypto_primitive,
            variant: n.quantum_status,
            nistStandard: n.nist_standard,
            targetReplacement: n.recommended_pqc,
          },
          retentionYears: n.data_retention_years,
          riskScore: n.risk_score,
          hndlExposure: n.hndl_exposure_horizon,
        },
        criticality: n.criticality,
      })),
      dependencies: graph.edges.map((e) => ({
        ref: e.source,
        dependsOn: [e.target],
        relationship: e.relationship,
      })),
    },
    null,
    2
  );

  // Generate Executive Summary
  const executiveReportOutput = `# Executive Cryptographic Agility & PQC Migration Readiness Report
Generated by CAMP-Graph on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

## 1. Executive Quantum Posture Summary
- Overall Infrastructure Quantum Risk Score: ${riskSummary.overall_risk_score}/100
- NIST FIPS 203/204/205 Compliance Progress: ${riskSummary.nist_compliance_percent}%
- Total Cryptographic Assets Scanned: ${riskSummary.total_assets}
- Quantum Vulnerable Assets: ${riskSummary.vulnerable_nodes_count}
- Hybrid (FIPS 203 Transition) Assets: ${riskSummary.hybrid_nodes_count}
- Post-Quantum Safe Assets: ${riskSummary.safe_nodes_count}
- Active Migration Blockers: ${riskSummary.blockers_count}
- Mosca Equation Timeline Status: ${riskSummary.mosca_timeline_status}
- Maximum Data Retention Shelf-Life: ${riskSummary.max_retention_years} Years

## 2. Harvest-Now-Decrypt-Later (HNDL) Threat Analysis
Adversaries actively harvest encrypted communications traversing public and internal gateways today to decrypt retroactively when Cryptanalytically Relevant Quantum Computers (CRQCs) emerge (estimated ~2029-2033).
${riskSummary.hndl_critical_count} assets feature data retention periods exceeding 10 years, necessitating immediate Phase 1 Hybridization (X25519 + ML-KEM-768).

## 3. NIST Post-Quantum Algorithm Mapping
- Key Encapsulation (KEM): NIST FIPS 203 (ML-KEM-512, ML-KEM-768, ML-KEM-1024)
- Digital Signatures: NIST FIPS 204 (ML-DSA-44, ML-DSA-65, ML-DSA-87)
- Stateless Hash Signatures: NIST FIPS 205 (SLH-DSA-128, SLH-DSA-256)
- Symmetric Bulk Encryption: AES-256-GCM / AES-256-XTS (Grover-hardened)

## 4. Current Asset CBOM Inventory
${graph.nodes.map((n, i) => `${i + 1}. **${n.label}** (${n.type})
   - Primitive: \`${n.crypto_primitive}\`
   - Quantum Status: **${n.quantum_status}** | Criticality: **${n.criticality}**
   - Retention: ${n.data_retention_years} yrs | Risk Score: ${n.risk_score}/100
   - Target NIST Standard: ${n.recommended_pqc} (${n.nist_standard})
`).join('\n')}
`;

  // Generate Federal NSM-10 / OMB M-23-02 Compliance Attestation (styled, printable HTML)
  const readinessRows = graph.nodes
    .slice()
    .sort((a, b) => b.risk_score - a.risk_score)
    .map((n) => {
      const statusColor = n.quantum_status === 'SAFE' ? '#0d2d1a' : (n.quantum_status === 'HYBRID' ? '#382306' : '#381014');
      const statusText = n.quantum_status === 'SAFE' ? '#7ee787' : (n.quantum_status === 'HYBRID' ? '#e3b341' : '#ff7b72');
      return `<tr>
        <td>${n.label}</td>
        <td>${n.type}</td>
        <td>${n.crypto_primitive}</td>
        <td style="background:${statusColor};color:${statusText};font-weight:700;text-align:center;">${n.quantum_status}</td>
        <td style="text-align:center;">${n.criticality}</td>
        <td style="text-align:center;">${n.data_retention_years}y</td>
        <td>${n.recommended_pqc} (${n.nist_standard})</td>
        <td style="text-align:center;">${n.risk_score}/100</td>
      </tr>`;
    })
    .join('\n');

  const federalComplianceOutput = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Federal PQC Migration Compliance Attestation</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; background: #f4f4f2; color: #1a1a1a; margin: 0; padding: 40px; }
  .sheet { max-width: 900px; margin: 0 auto; background: #fff; padding: 56px 64px; box-shadow: 0 0 24px rgba(0,0,0,0.15); }
  .seal { text-align: center; font-size: 11px; letter-spacing: 2px; text-transform: uppercase; color: #555; margin-bottom: 4px; }
  h1 { text-align: center; font-size: 22px; margin: 8px 0 0; }
  h2 { font-size: 15px; border-bottom: 2px solid #1a1a1a; padding-bottom: 4px; margin-top: 36px; }
  .subtitle { text-align: center; font-size: 12px; color: #555; margin-top: 4px; }
  .meta { font-size: 12px; margin-top: 24px; border: 1px solid #ccc; padding: 12px 16px; background: #fafafa; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; margin-top: 12px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
  th { background: #1a1a1a; color: #fff; text-transform: uppercase; font-size: 10px; letter-spacing: 0.5px; }
  .milestones { list-style: none; padding: 0; margin-top: 12px; }
  .milestones li { padding: 8px 0; border-bottom: 1px dashed #ccc; font-size: 12px; display: flex; justify-content: space-between; }
  .milestones li b { color: #1a1a1a; }
  .verdict { margin-top: 16px; padding: 16px; border: 2px solid #1a1a1a; font-size: 13px; }
  .signoff { margin-top: 48px; display: flex; justify-content: space-between; }
  .sig-block { width: 45%; }
  .sig-line { border-top: 1px solid #1a1a1a; margin-top: 40px; padding-top: 4px; font-size: 11px; }
  .footer-note { margin-top: 40px; font-size: 10px; color: #777; text-align: center; }
</style>
</head>
<body>
  <div class="sheet">
    <div class="seal">Federal Post-Quantum Cryptography Migration Attestation</div>
    <h1>Cryptographic Agility &amp; PQC Migration Readiness Certification</h1>
    <p class="subtitle">Prepared in accordance with White House National Security Memorandum 10 (NSM-10),<br/>
    OMB Memorandum M-23-02 (Migrating to Post-Quantum Cryptography), and the CISA/NIST PQC Migration Playbook</p>

    <div class="meta">
      <strong>Report Generated:</strong> ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}<br/>
      <strong>System of Record:</strong> CAMP-Graph Cryptographic Agility &amp; PQC Migration Engine v1.0.0<br/>
      <strong>Total Cryptographic Assets in Scope:</strong> ${riskSummary.total_assets}<br/>
      <strong>Overall Quantum Risk Score:</strong> ${riskSummary.overall_risk_score}/100 &nbsp;|&nbsp;
      <strong>NIST FIPS 203/204/205 Compliance:</strong> ${riskSummary.nist_compliance_percent}%
    </div>

    <h2>1. Executive Attestation Summary</h2>
    <p style="font-size:12px;line-height:1.6;">
      This memorandum attests to the current cryptographic posture of the in-scope information system(s) relative to the
      requirements of NSM-10 and OMB M-23-02, which direct federal agencies (and, by extension, agencies' regulated and
      contracted entities) to inventory cryptographic assets vulnerable to cryptanalytically relevant quantum computers
      (CRQC) and to prioritize migration to NIST-standardized post-quantum algorithms. As of this report, ${riskSummary.vulnerable_nodes_count}
      of ${riskSummary.total_assets} assets remain quantum-vulnerable, ${riskSummary.hybrid_nodes_count} operate under hybrid
      classical/PQC protection, and ${riskSummary.safe_nodes_count} have completed migration to pure NIST PQC primitives.
      ${riskSummary.hndl_critical_count} assets carry Harvest-Now-Decrypt-Later (HNDL) critical exposure (data retention
      &ge; 10 years), and Mosca's timeline status is currently assessed as <b>${riskSummary.mosca_timeline_status.replace('_', ' ')}</b>.
    </p>

    <h2>2. Asset Readiness Matrix</h2>
    <table>
      <thead>
        <tr><th>Asset</th><th>Type</th><th>Current Primitive</th><th>Quantum Status</th><th>Criticality</th><th>Retention</th><th>Target PQC</th><th>Risk</th></tr>
      </thead>
      <tbody>
        ${readinessRows}
      </tbody>
    </table>

    <h2>3. Migration Timeline Milestones (NSM-10 / OMB M-23-02 Aligned)</h2>
    <ul class="milestones">
      <li><span><b>2026 &ndash; 2027</b>: Complete cryptographic asset inventory (CBOM); classify HNDL-critical systems; begin Phase 1 hybrid (X25519 + ML-KEM-768) deployment on external-facing key exchange.</span></li>
      <li><span><b>2027 &ndash; 2028</b>: Complete Phase 1 hybridization across all HIGH criticality assets; remediate identified migration blockers (legacy TLS 1.1 / hardcoded RSA-1024 systems).</span></li>
      <li><span><b>2028 &ndash; 2030</b>: Phase 2 &ndash; migrate digital signature infrastructure to ML-DSA / SLH-DSA (FIPS 204/205); retire vulnerable symmetric primitives below AES-256.</span></li>
      <li><span><b>2030 &ndash; 2031</b>: Phase 3 &ndash; complete migration of remaining asymmetric key establishment to pure ML-KEM; validate NIST security level compliance across the estate.</span></li>
      <li><span><b>2031 &ndash; 2033</b>: Full cryptographic agility posture achieved; continuous monitoring for CRQC timeline updates and NIST standard revisions; agency-wide OMB M-23-02 close-out reporting.</span></li>
    </ul>

    <h2>4. Compliance Verdict</h2>
    <div class="verdict">
      ${
        riskSummary.overall_risk_score <= 15 && riskSummary.vulnerable_nodes_count === 0
          ? '<b>ATTESTED COMPLIANT:</b> All in-scope cryptographic assets have achieved hybrid or pure NIST PQC protection consistent with NSM-10 and OMB M-23-02 migration expectations for the current reporting period.'
          : `<b>CONDITIONAL / IN-PROGRESS:</b> ${riskSummary.vulnerable_nodes_count} asset(s) remain quantum-vulnerable and ${riskSummary.blockers_count} active migration blocker(s) require remediation. Continued phased migration is required to reach full NSM-10 / OMB M-23-02 attestation.`
      }
    </div>

    <div class="signoff">
      <div class="sig-block">
        <div class="sig-line">Chief Information Security Officer (CISO) &mdash; Signature &amp; Date</div>
      </div>
      <div class="sig-block">
        <div class="sig-line">Agency Post-Quantum Migration Lead &mdash; Signature &amp; Date</div>
      </div>
    </div>

    <p class="footer-note">
      This document is a machine-generated compliance attestation draft produced by CAMP-Graph for internal review.
      It does not constitute a formal OMB or CISA filing until reviewed, countersigned, and submitted through the
      agency's designated compliance channel.
    </p>
  </div>
</body>
</html>`;

  const handleCopy = (content: string) => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const activeContent =
    activeTab === 'CYCLONEDX'
      ? cycloneDxOutput
      : activeTab === 'EXECUTIVE_REPORT'
      ? executiveReportOutput
      : activeTab === 'FEDERAL_COMPLIANCE'
      ? federalComplianceOutput
      : JSON.stringify(graph, null, 2);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="w-full max-w-3xl bg-[#161b22] border border-[#30363d] rounded-lg shadow-2xl overflow-hidden flex flex-col max-h-[90vh] font-sans">
        
        {/* Header */}
        <div className="p-3 border-b border-[#30363d] flex items-center justify-between bg-[#0d1117]">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-[#0d2d1a] rounded text-[#7ee787] border border-[#238636]">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-xs font-bold text-[#f0f6fc]">Export Cryptographic Asset & PQC Audit Report</h3>
              <p className="text-[10px] text-[#8b949e]">Download standards-compliant CBOM and executive audit briefing</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-[#8b949e] hover:text-[#f0f6fc] rounded hover:bg-[#21262d] transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tab selector */}
        <div className="px-3 pt-2 flex gap-1.5 border-b border-[#30363d] bg-[#0d1117]/60 font-mono text-xs">
          <button
            onClick={() => setActiveTab('EXECUTIVE_REPORT')}
            className={`px-3 py-1.5 text-xs font-bold rounded-t transition-colors ${
              activeTab === 'EXECUTIVE_REPORT'
                ? 'bg-[#161b22] text-[#7ee787] border-t border-x border-[#30363d]'
                : 'text-[#8b949e] hover:text-[#f0f6fc]'
            }`}
          >
            Executive Summary (.md)
          </button>
          <button
            onClick={() => setActiveTab('CYCLONEDX')}
            className={`px-3 py-1.5 text-xs font-bold rounded-t transition-colors ${
              activeTab === 'CYCLONEDX'
                ? 'bg-[#161b22] text-cyan-300 border-t border-x border-[#30363d]'
                : 'text-[#8b949e] hover:text-[#f0f6fc]'
            }`}
          >
            CycloneDX 1.6 CBOM (.json)
          </button>
          <button
            onClick={() => setActiveTab('RAW_GRAPH')}
            className={`px-3 py-1.5 text-xs font-bold rounded-t transition-colors ${
              activeTab === 'RAW_GRAPH'
                ? 'bg-[#161b22] text-indigo-300 border-t border-x border-[#30363d]'
                : 'text-[#8b949e] hover:text-[#f0f6fc]'
            }`}
          >
            Graph Topology Schema
          </button>
          <button
            onClick={() => setActiveTab('FEDERAL_COMPLIANCE')}
            className={`px-3 py-1.5 text-xs font-bold rounded-t transition-colors flex items-center gap-1.5 ${
              activeTab === 'FEDERAL_COMPLIANCE'
                ? 'bg-[#161b22] text-amber-300 border-t border-x border-[#30363d]'
                : 'text-[#8b949e] hover:text-[#f0f6fc]'
            }`}
          >
            <Landmark className="w-3 h-3" />
            <span>Federal Compliance Attestation</span>
          </button>
        </div>

        {/* Content Viewer */}
        <div className="p-3 flex-1 overflow-y-auto">
          <pre className="p-2.5 bg-[#090d16] rounded border border-[#30363d] text-[#f0f6fc] font-mono text-[10.5px] max-h-96 overflow-x-auto leading-relaxed">
            <code>{activeContent}</code>
          </pre>
        </div>

        {/* Footer */}
        <div className="p-3 border-t border-[#30363d] bg-[#0d1117] flex items-center justify-between font-mono">
          <span className="text-[11px] text-[#8b949e]">
            {graph.nodes.length} Assets | {graph.edges.length} Dependencies
          </span>

          <div className="flex items-center gap-2">
            <button
              onClick={() => handleCopy(activeContent)}
              className="px-3 py-1 bg-[#21262d] hover:bg-[#30363d] text-[#c9d1d9] rounded text-xs font-bold flex items-center gap-1.5 transition-colors border border-[#30363d]"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-[#3fb950]" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>

            <button
              onClick={() => {
                const filename =
                  activeTab === 'CYCLONEDX'
                    ? 'cyclonedx-cbom-1.6.json'
                    : activeTab === 'EXECUTIVE_REPORT'
                    ? 'pqc-migration-readiness-report.md'
                    : activeTab === 'FEDERAL_COMPLIANCE'
                    ? 'nsm10-omb-m2302-compliance-attestation.html'
                    : 'camp-graph.json';
                const mime =
                  activeTab === 'EXECUTIVE_REPORT'
                    ? 'text/markdown'
                    : activeTab === 'FEDERAL_COMPLIANCE'
                    ? 'text/html'
                    : 'application/json';
                handleDownload(activeContent, filename, mime);
              }}
              className="px-3.5 py-1 bg-[#238636] hover:bg-[#2ea043] text-white rounded text-xs font-bold flex items-center gap-1.5 shadow transition-all border border-[#3fb950]"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
